spring:
  datasource-data:
    jdbc-url: jdbc:mysql://${RDS_HOST}:${RDS_PORT}/${RDS_DB_NAME}?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  datasource-meta:
    jdbc-url: jdbc:mysql://${RDS_HOST}:${RDS_PORT}/${RDS_META_DB_NAME}?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate

  batch:
    jdbc:
      initialize-schema: always

logging:
  level:
    org.hibernate.SQL: INFO
