spring:
  datasource-data:
    jdbc-url: jdbc:mysql://${DB_HOST:mysql}:${DB_PORT:3306}/${DB_NAME:focus_db}?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
