spring:
  application:
    name: focus-to-levelup-admin

  profiles:
    active: ${SPRING_PROFILE:local}

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        hbm2ddl:
          auto: validate

  thymeleaf:
    cache: true

admin:
  initial:
    username: ${ADMIN_INITIAL_USERNAME:}
    password: ${ADMIN_INITIAL_PASSWORD:}

management:
  endpoints:
    web:
      exposure:
        include: health

server:
  port: ${ADMIN_SERVER_PORT:8081}
