name: CI/CD for Production (Docker Compose)

on:
  push:
    tags:
      - '*'

permissions:
  contents: read

jobs:
  call-cicd-template:
    name: Deploy API for Production
    uses: ./.github/workflows/cicd-template.yml
    secrets: inherit
    with:
      environment: 'prod'
      module_name: 'api'
      gradle_task: ':levelup-application:api:bootJar'
      module_dir: 'levelup-application/api'
      deploy_strategy: 'bluegreen'
